<%@include file="../shared/header.jsp" %>
<ul class="list-group">
  <li class="list-group-item">There are three different species of elephant ? the African Savannah elephant, the African Forest elephant and the Asian elephant. Elephants are known for their large ears, tusks made of ivory and their trunks ? which are actually a fusion of their nose and upper lip.</li>
  <li class="list-group-item">Elephants are the world?s largest land animal! Male African elephants can reach 3m tall and weigh between 4,000 -7,500kg. Asian elephants are slightly smaller, reaching 2.7m tall and weighing 3,000? 6,000kg. They are known for their large ears, tusks made of ivory and their trunks ? which are actually a fusion of their nose and upper lip.</li>
  <li class="list-group-item">There?s an easy way to tell the African elephants apart from their Asian cousins ? their ears! African elephants have large ears shaped like the continent of Africa! Asian elephants? ears are smaller and shaped like India. Cool, huh?</li>
  <li class="list-group-item">You can tell a lot about an elephant by looking at their tusks! Elephant tusks never stop growing, so enormous tusks can be a sign of an old elephant. Both male and female African elephants grow tusks, but only male Asian elephants grow them. A tusk-less adult elephant is likely to be a female Asian elephant.</li>
  <li class="list-group-item">Until recently, African Forest elephants were thought to be a subspecies of the African elephant, but new research discovered that they are actually a separate species entirely. These elephants live in the tropical forests of Africa?s Congo Basin. They have straighter tusks and more rounded ears than Savannah elephants.</li>
  <li class="list-group-item">These magnificent mammals spend between 12 to 18 hours eating grass, plants and fruit every single day! They use their long trunks to smell their food and lift it up into their mouth ? yum!</li>
  <li class="list-group-item">All that eating means one thing, gang, an awful lot of poo! Each elephant creates about one tonne of poo per week, which keeps the soil fertile and disperses tree seeds. Elephants also dig waterholes and create footpaths, literally changing the landscape around them!</li>
  <li class="list-group-item">In Mount Elgon National Park in Kenya, a group of elephants use their tusks to mine for salt in underground caves! They feel their way around with their trunks and eat the salts by breaking them off with their tusks.</li>
  <li class="list-group-item"> Elephants have created their very own sunscreen! After a river or swamp bath, they?ll throw mud and sand up and over themselves to protect their skin from the hot, burning sun. Clever!</li>
  <li class="list-group-item">Sadly, elephants are in trouble. Many are killed by humans for their ivory tusks, because they?ve come into conflict with communities or simply for sport. There are far fewer Asian elephants (which are categorised as Endangered) than there are African elephants (listed as Vulnerable ? at risk of becoming Endangered). Asian elephants also face threats from tourist attractions where people pay to ride on their backs or watch them paint pictures using their trunks.</li>
</ul>
<%@include file="../shared/footer.jsp" %>